# Generated by Django 3.2.4 on 2021-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_linkedincredentials_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedincredentials',
            name='password',
            field=models.BinaryField(max_length=200),
        ),
    ]
